config/routes.rb
SampleApp::Application.routes.draw do

  root to: "static_pages#home"
  match '/signup',  to: 'users#new',via: 'get'
  match '/signin' =>  "sessions#new", via: :get
  match '/signout' => "sessions#destroy", via: :delete

  resources :static_pages, except: [:index, :new, :create, :show, :update, :edit, :destroy] do
    collection do
      get :help
      get :about
      get :contact
      get :sign_up
      get :sign_in
    end
  end

  resources :users do

  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :microposts, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  default_scope -> { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy

  validates_presence_of :name
  validates_length_of :name, maximum: 25

  validates_presence_of :email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates_uniqueness_of :email, case_sensitive: false

  validates_presence_of :password
  validates_length_of :password, minimum: 6

  before_save { email.downcase! }
  before_create :create_remember_token

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  #layout false

  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user,  only: [:edit, :update, :index]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user,      only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 30)
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      flash.now[:error] = "Error"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  #Returns the Gravatar (http://gravatar.com) for given user
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{href: "http://railstutorial.org/"}
      Rails Tutorial
    by Michael Hartl
    %nav
      %ul
        %li
          =link_to "About", about_static_pages_path
        %li
          =link_to "Contact", contact_static_pages_path
        %li
          %a{href: "http://news.railstutorial.org/"}
            News

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "sample app", '#', id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to "Home", root_path
          %li= link_to "Help", help_static_pages_path
          - if signed_in?
            %li= link_to "Users", users_path
            %li.dropdown
              %a.dropdown_toggle{href: "#", "data-toggle" => "dropdown" }
                Acccount
                %b.caret
              %ul.drop_down-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li= link_to "Sign out", signout_path, method: :delete
          - else
            %li= link_to "Sign In", signin_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'

    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
      = render 'layouts/footer'
      =debug(params) if Rails.env.development?

app/views/microposts/_micropost.html.haml
%li
  %span.content #{micropost.content}
  %span.timestamp
    Posted #{time_ago_in_words(micropost.created_at)} ago.

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  .error_explanation
    .alert.alert-danger
      The form contains #{pluralize(@user.errors.count, "error")}
    %ul
      - @user.errors.full_messages.each do |error|
        %li #{error}

app/views/static_pages/about.html.haml
- provide(:title, "About Us")
%h1
  About Us
%p
  The
  %a{href: "http://railstutorial.org/"}
    Ruby on Rails Tutorial
  is a project to make a book and screencasts to teach web development with
  %a{href: "http://rubyonrails.org"}
    Ruby on Rails
  This is the sample application for the tutorial

app/views/static_pages/contact.html.haml
- provide(:title, "Contact")
%h1
  Contact
%p
  Contact Ruby on Rails Tutorial about the sample app at the
  %a{href: "http://railstutorial.org/contact"}
    contact page

app/views/static_pages/help.html.haml
- provide(:title, "Help")
%h1 Help
%p
  Get help on Ruby on Rails Tutorial at the
  %a{href: "http://railstutorial.org/help"}
    Rails Tutorial help page
  To get help on this sample app, see the
  %a{href: 'http://railstutorial.org/book'}
    Rails Tutorial book

app/views/static_pages/home.html.haml
.center.hero-unit
  %h1 Welcome to the Sample App

  %h2
    This is the home page for the
    %a{href: "http://railstutorial.org/"} Ruby on Rails Tutorial
    sample application.
  =link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"
= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'

app/views/users/_user.html.haml
%li
  = gravatar_for(user, size: 52)
  = link_to user.name, user
  -if current_user.admin? && !current_user?(user)
    = link_to '| delete', user, method: :delete, data: {confirm: "Are you sure?"}

app/views/users/edit.html.haml
- provide(:title, "Edit user")
%h1 Update your profile

.row
  .col-md-6.col-md-offset-3
    =form_for @user do |user|
      = render 'shared/error_messages'

      = user.label :name
      = user.text_field :name

      = user.label :email
      = user.text_field :email

      = user.label :password
      = user.password_field :password

      = user.label :password_confirmation
      = user.password_field :password_confirmation

      = user.submit "Save changes", class: "btn btn-large btn-primary"

    = gravatar_for @user
    = link_to "change", 'http://gravatar.com/emails'

app/views/users/index.html.haml
- provide(:title, "All users")
%h1 All users

=will_paginate

%ul.users
  =render @users

=will_paginate

app/views/users/new.html.haml
- provide(:title, "Sign up")
%h1 Sign up

.row
  .col-md-6.col-md-offset-3
    =form_for @user do |user|
      = render 'shared/error_messages'

      .form-group
        = user.label :name
        = user.text_field :name

      .form-group
        = user.label :email
        = user.text_field :email

      .form-group
        = user.label :password
        = user.password_field :password

      .form-group
        = user.label :password_confirmation
        = user.password_field :password_confirmation

      = user.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.haml
= provide(:title, @user.name)
.row
  .col-md-4
    %section
      %h1
        = gravatar_for @user, size: 50
        = @user.name
  .span8
    -if @user.microposts.any?
      %h3 Microposts (#{@user.microposts.count})
      %ol.microposts
        = render @microposts
      = will_paginate @microposts